### ISSUE TITLE
console and setup binaries

### ISSUE THREAD

**Issue by ZeroChaos-** [rapid7/rex-random_identifier#2]
This seems to ship console and setup the same as rex-text, do both gems really need to ship these?

**Comment by sempervictus** [comment]
When debugging them such things help, and provides more of a consistent structure for all the different folks using it or hacking on it. Any reason one would want to drop these artifacts?

**Comment by ZeroChaos-** [comment]
when this gem is installed, these binaries collide with rex-text and other rapid7 gems because so many of them seem to ship them.  It's not a crisis, just seems a bit weird.

**Comment by busterb** [comment]
I believe they just need to be deleted - they were all generated from the same template.

**Comment by busterb** [comment]
fixed in 10e164a, I'll take a look at others that also need the same treatment. Thanks!

**Comment by busterb** [comment]
I had removed these a while ago from rex-text already. If you see others, let me know and we'll zap em.
